export const PARAM = {
  loss: "损失参数",
  epochs:"迭代次数",
  batch_size:"批量大小：控制优化方法每次优化所使用的样本数量",
  SBO:"记录最优验证结果",
  leraning_rate:"学习率：控制算法训练速度",
  epoch:"训练轮数：控制算法训练轮数",
  embedding_dim:"词向量维度",
  metrics:"度量函数",
  max_num_words:"最大词数",
  optimizer:"优化法",
  batch_input_shape:"每批输入张量结构",
  strides:"池化步长",
  padding:"滤波器对于边界的处理方式",
  kernel_size:"控制算法训练速度",
  pool_size:"池化大小",
  filters:"滤波器数量",
  activation:"激活函数",
  nb_blocks:"残差块包含细胞块数",
  downsample:"下采样",
  out_channels:"输出通道",
  cardinality:"基数",
  out_dim:"输出维度",
  output_dim:"输出维度",
  input_dim:"输入维度",
  Dropout:"dropout层概率",
}

